export const CREATE_ORDER_REQUEST = 'CREATE_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const GET_ALL_ORDER_REQUEST = 'GET_ALL_ORDER_REQUEST';
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';
export const GET_ALL_ORDER_FAILURE = 'GET_ALL_ORDER_FAILURE';

export const REMOVE_FROM_ORDER_REQUEST = 'REMOVE_FROM_ORDER_REQUEST';
export const REMOVE_FROM_ORDER_SUCCESS = 'REMOVE_FROM_ORDER_SUCCESS';
export const REMOVE_FROM_ORDER_FAILURE = 'REMOVE_FROM_ORDER_FAILURE';

export const UPDATE_IS_PAID_REQUEST = 'UPDATE_IS_PAID_REQUEST';
export const UPDATE_IS_PAID_SUCCESS = 'UPDATE_IS_PAID_SUCCESS';
export const UPDATE_IS_PAID_FAILURE = 'UPDATE_IS_PAID_FAILURE';
