export const CREATE_REQUEST = 'CREATE_REQUEST';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';

export const GET_REQUEST = 'GET_REQUEST';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_FAILURE = 'GET_FAILURE';

export const GET_BY_ID_REQUEST = 'GET_By_ID_REQUEST';
export const GET_BY_ID_SUCCESS = 'GET_By_ID_SUCCESS';
export const GET_BY_ID_FAILURE = 'GET_By_ID_FAILURE';

export const GET_BY_SEARCH_REQUEST = 'GET_BY_SEARCH_REQUEST';
export const GET_BY_SEARCH_SUCCESS = 'GET_BY_SEARCH_SUCCESS';
export const GET_BY_SEARCH_FAILURE = 'GET_BY_SEARCH_FAILURE';

export const UPDATE_BY_ID_REQUEST = 'UPDATE_BY_ID_REQUEST';
export const UPDATE_BY_ID_SUCCESS = 'UPDATE_BY_ID_SUCCESS';
export const UPDATE_BY_ID_FAILURE = 'UPDATE_BY_ID_FAILURE';

export const SOFT_DELETE_BY_ID_REQUEST = 'SOFT_DELETE_BY_ID_REQUEST';
export const SOFT_DELETE_BY_ID_SUCCESS = 'SOFT_DELETE_BY_ID_SUCCESS';
export const SOFT_DELETE_BY_ID_FAILURE = 'SOFT_DELETE_BY_ID_FAILURE';